use async_channel::Sender;
use iced::{keyboard, mouse, window};

use crate::core::config;
use crate::sys::pty::PtyCommand;

use super::nova::{ColorField, SettingsTab};

#[derive(Debug, Clone)]
pub enum Message {
  Type(Vec<u8>),
  NewTab,
  CloseTab(usize),
  PtyReady(usize, Sender<PtyCommand>),
  PtyOutputReceived(usize, Vec<u8>),
  PtyExited(usize),
  CloseActiveTab,
  NextTab,
  PrevTab,
  CloseWindow,
  MinimizeWindow,
  MaximizeWindow,
  DragWindow,
  WindowOpened(window::Id),
  WindowFocused,
  WindowUnfocused,
  WindowResized(f32, f32),
  WindowMaximizedState(bool),
  PasteRequested,
  ClipboardReceived(Option<String>),
  OpenSettings,
  OpenShellPicker,
  CloseShellPicker,
  NewTabWithShell(String),
  CursorMoved(iced::Point),
  MousePressed(mouse::Button),
  MouseReleased(mouse::Button),
  CopySelection,
  Tick,
  BellBlinkTick,
  CursorBlinkTick,
  CloseSettings,
  SettingsTabSelected(SettingsTab),
  SettingsEditorChanged(String),
  SettingsBellChanged(config::BellType),
  SettingsShellInputChanged(String),
  SettingsAddShell,
  SettingsRemoveShell(usize),
  SettingsFontFamilyChanged(String),
  SettingsFontSizeChanged(f32),
  SettingsColorChanged(ColorField, String),
  SettingsStatusBarToggled(bool),
  SettingsDateFormatChanged(String),
  SettingsTimeFormatChanged(String),
  SettingsStartRecordKb(usize),
  SettingsRecordKb {
    key: keyboard::Key,
    modifiers: keyboard::Modifiers,
  },
  SettingsCancelRecordKb,
  SettingsResetKb(usize),
  SettingsResetAll,
  Scroll(f32),
  ModifiersChanged(keyboard::Modifiers),
  OpenCommandPalette,
  CloseCommandPalette,
  PaletteQueryChanged(String),
  PaletteNavigate(i32),
  PaletteConfirm,
  PaletteSelectAndConfirm(usize),
  OpenAskAi,
  CloseAiOverlay,
  AiOverlayInputChanged(String),
  AiSubmit,
  AiResponseReceived(Result<String, String>),
  ExplainError,
  CopyCodeBlock(String),
  RunCodeInTerminal(String),
  SettingsAiProviderChanged(config::AiProvider),
  SettingsAiModelChanged(String),
  SettingsAiApiKeyChanged(String),
  SettingsAiBaseUrlChanged(String),
  SettingsWindowControlsChanged(config::WindowControls),
  SettingsCursorStyleChanged(config::CursorStyle),
  SettingsCursorBlinkToggled(bool),
  SettingsInitialCommandChanged(String),
  SettingsWaitAfterCommandToggled(bool),
  DiagnosticBannerResponse(Result<String, String>),
  DiagnosticBannerCommand(String),
  SettingsDiagnosticBannerToggled(bool),
  SplitPane,
  CloseSplitPane,
  CloseLeftPane,
  ResizeSettled(u64),
  FontSizeUp,
  FontSizeDown,
  FontSizeReset,
  FontResizeSettled(u64),
  SearchOpen,
  SearchClose,
  SearchQueryChanged(String),
  SearchDebounced(u64),
  SearchNext,
  SearchPrev,
  NoOp,
  NotificationActivated,
  Osc52ReadResponse(usize, Option<String>),
  PasteWarningConfirm,
  PasteWarningCancel,
}
